In [2]:
import numpy as np

In [3]:
lst1 = [1,2,3,4,5]

In [4]:
arr1 = np.array(lst1)

In [5]:
arr1

array([1, 2, 3, 4, 5])

In [6]:
lst2 = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
arr2 = np.array(lst2)

In [8]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr3 = np.arange(0,11,3)
arr3

array([0, 3, 6, 9])

In [11]:
arr4 = np.zeros(3)
arr4

array([0., 0., 0.])

In [14]:
arr5 = np.zeros((4,1))
arr5

array([[0.],
       [0.],
       [0.],
       [0.]])

In [15]:
arr5 = np.zeros((5,3))
arr5

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
arr6 = np.ones(5)
arr6

array([1., 1., 1., 1., 1.])

In [17]:
arr7 = np.ones((4,1))
arr7

array([[1.],
       [1.],
       [1.],
       [1.]])

In [18]:
arr8 = np.ones((4,5))
arr8

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
arr9 = np.linspace(0,5,10)
arr9

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [25]:
arr10 = np.eye(4)
arr10

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
np.random.rand(5)

array([0.96108758, 0.41233855, 0.53907975, 0.46020991, 0.95351097])

In [27]:
np.random.rand(5,3)

array([[0.77176246, 0.24018389, 0.38451724],
       [0.18518097, 0.98316336, 0.04631039],
       [0.72858592, 0.24218784, 0.55824039],
       [0.2225839 , 0.49660806, 0.23106897],
       [0.12077075, 0.42474677, 0.27561029]])

In [28]:
np.random.randn(3)

array([-0.53026657,  0.30193553, -0.16045261])

In [30]:
np.random.randn(3,5)

array([[ 0.19152128, -0.43934359, -2.05799551,  1.68860056,  0.99677708],
       [ 0.85668014, -0.65577559,  1.47145413,  0.39034257,  2.0684544 ],
       [-0.32492155, -0.37211328, -0.32068144,  0.47829417,  0.35076997]])

In [36]:
np.random.randint(1,100)

53

In [37]:
np.random.randint(1,100,5)

array([38, 17, 62, 74, 53])

In [38]:
ar = np.arange(25)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
ar.shape

(25,)

In [40]:
ar.dtype

dtype('int32')

In [41]:
ar.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
ar.reshape(5,5).shape

(5, 5)

In [43]:
rar = np.random.randint(2,50,10)

In [44]:
rar

array([24, 15, 21,  9,  8,  6, 12, 40, 13, 23])

In [45]:
rar.max()

40

In [47]:
rar.min()

6

In [48]:
rar.argmax()

7

In [49]:
rar.argmin()

5

In [50]:
from numpy.random import randint

In [51]:
randint(2,10,5)

array([4, 5, 5, 3, 3])

In [53]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr[5]

6

In [56]:
arr[:7]

array([1, 2, 3, 4, 5, 6, 7])

In [57]:
s_arr = arr[2:6]
s_arr

array([3, 4, 5, 6])

In [58]:
s_arr[:] = 100

In [59]:
s_arr

array([100, 100, 100, 100])

In [60]:
arr

array([  1,   2, 100, 100, 100, 100,   7,   8,   9,  10])

In [61]:
c_arr = arr.copy();
c_arr

array([  1,   2, 100, 100, 100, 100,   7,   8,   9,  10])

In [62]:
c_arr[0] = 1000
c_arr

array([1000,    2,  100,  100,  100,  100,    7,    8,    9,   10])

In [63]:
arr

array([  1,   2, 100, 100, 100, 100,   7,   8,   9,  10])

In [64]:
arr2d = np.arange(0,25).reshape(5,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [65]:
arr2d[2][2]

12

In [66]:
arr2d[2,2]

12

In [67]:
arr2d[2:4,2:4]

array([[12, 13],
       [17, 18]])

In [69]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
b_arr = arr>5
b_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [71]:
arr[b_arr]

array([ 6,  7,  8,  9, 10])

In [72]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
arr[arr>6]

array([ 7,  8,  9, 10])